# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# Fonts
font_family      JetBrains Mono Nerd Font
bold_font        JetBrains Mono Nerd Font
italic_font      JetBrains Mono Nerd Font
bold_italic_font JetBrains Mono Nerd Font

font_size 11
background_opacity 0.7

# window settings
# initial_window_width 95c
# initial_window_height 35c
window_padding_width 5
confirm_os_window_close 0

background #001217
#001e26 -- Original
foreground #93a1a1
cursor #93a1a1

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #268bd2
inactive_tab_foreground #CAD3F5
inactive_tab_background #586e75
tab_bar_background      #073642

selection_background #fcf4dc
selection_foreground #001e26

# Suggested command color adjustment
color8 #586e75

# Color palette
color0  #002b36
color1  #dc322f
color2  #859900
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #e9e2cb
color8  #586e75
color9  #cb4b16
color10 #465a61
color11 #52676f
color12 #708183
color13 #6c71c4
color14 #81908f
color15 #fcf4dc
